Add an Image Fetcher Example
omichel/test_world pull request #15
Opened 2019-08-12 09:49 UTC by DavidMansolino

see https://github.com/aiwc/test_world/issues/58#issuecomment-520336505

2019-08-12 13:21 UTC, DavidMansolino commented on controllers/supervisor/image_frame_buffer.py
> +                    ret.append([xStart, yStart, xLength, yLength, base64.standard_b64encode(bytes(pixels))])
The base64 encoding is sometimes returning strange values such as:
> ...'\\x00', '\\xff', **'{'**, **'{'**, **'{'**, '\\xff', '\\x00', '\\xd1'...

Not sure to understand where does these `{` come from

2019-08-13 06:57 UTC, DavidMansolino commented
Almost :smile: 

![Capture du 2019-08-13 08-56-47](https://user-images.githubusercontent.com/2461619/62921214-533a5d00-bda8-11e9-891e-42bf3c3228e9.png)

2019-08-13 09:01 UTC, DavidMansolino commented
:tada: 

![Capture du 2019-08-13 10-59-57](https://user-images.githubusercontent.com/2461619/62928873-9ea93700-bdb9-11e9-871f-00234e1c2446.png)

As expected, the actual fix was a one-line detail:  1a99ffb36118f552f457c0a1f7761f43a1d7f763

2019-08-13 09:03 UTC, DavidMansolino commented
:+1:

2019-08-13 09:08 UTC, omichel commented
:eyes:

2019-08-13 09:29 UTC, omichel requested changes

2019-08-13 09:29 UTC, omichel commented on controllers/supervisor/image_frame_buffer.py
> +#!/usr/bin/python3
```suggestion
#!/usr/bin/env python3
```

2019-08-13 09:29 UTC, omichel commented on controllers/supervisor/image_frame_buffer.py
> +                    ret.append([xStart, yStart, xLength, yLength, base64.b64encode(bytes(pixels)).decode("utf-8")])
```suggestion
                    ret.append([xStart, yStart, xLength, yLength, base64.b64encode(bytes(pixels)).decode()])
```
utf-8 is the default encode value.

2019-08-13 09:29 UTC, omichel commented on examples_new/general_image-fetch_py/general_image-fetch.py
> +    print(sys.path)
Is that a debug message?

```suggestion
```

2019-08-13 09:29 UTC, omichel commented on controllers/supervisor/supervisor.py
> +            message = 'aiwc.' + message.split('aiwc.', 1)[-1]
That seems dangerous to trash part of the message... Instead, we should ensure that this part of the message was processed before (and thus we could remove these two lines).

2019-08-13 09:31 UTC, DavidMansolino commented on controllers/supervisor/image_frame_buffer.py
> +#!/usr/bin/python3
That was to be homogeneous with the previous version of the controllers: https://github.com/aiwc/examples/blob/ae937e69e40b82159e21861d86852c5ae4425321/commentator_skeleton_py/commentator_skeleton.py#L1

But your version seems indeed more correct.

2019-08-13 10:15 UTC, DavidMansolino commented
:+1:

2019-08-13 10:23 UTC, omichel commented on examples_new/general_image-fetch_py/general_image-fetch.py
> +#!/usr/bin/python3
```suggestion
#!/usr/bin/env python3
```

2019-08-13 10:55 UTC, DavidMansolino commented
:+1:

2019-08-13 10:58 UTC, omichel approved these changes
Thank you!

2019-08-13 12:10 UTC, merged